Style/FrozenStringLiteralComment:
  EnforcedStyle: never
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: consistent_comma

